services:
  next_strapi:
    container_name: next_strapi
    hostname: next_strapi
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: next-strapi
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/.PostgressData/postgresonly/next_strapi:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432